// Configuration éditoriale V1. Toute mention PLACEHOLDER reste à remplacer.
export const APP_VERSION = "1.4.61";

// D8 is deliberately late: the distant future precedes the return to Majorca.
const JOURNEY_CHAPTERS = [
  { id: "thursday", challenges: [1, 2], pause: { id: "pause-1", after: 2, next: 3, target: "2026-09-18T12:00:00+02:00", label: "Vendredi 18 septembre à 12 h", text: ["Deux souvenirs retrouvés.", "On s'arrête ici pour ce soir.<br>On reprend demain, dans l'avion."], extra: "En attendant, quel souvenir aimerais-tu emporter partout avec toi ?" } },
  { id: "friday", challenges: [3, 5], pause: { id: "pause-2", after: 5, next: 6, target: "2026-09-19T08:00:00+02:00", label: "Samedi 19 septembre à 8 h", text: ["Ça fait beaucoup de kilomètres pour aujourd'hui.", "Le carnet peut se refermer un moment.", "Demain, nous irons encore un peu plus loin.", "Pas sur la route.", "Dans le temps.", "Profite de cette soirée.<br>Je serai là demain matin."] } },
  { id: "saturday-morning", challenges: [6, 7], pause: { id: "pause-3", after: 7, next: 8, target: "2026-09-19T18:00:00+02:00", label: "Samedi 19 septembre à 18 h", text: ["On a déjà parcouru beaucoup d'années aujourd'hui.", "Lenny et Milan ont grandi.", "Et pourtant, le carnet<br>n'est pas encore arrivé au bout.", "Il reste un dernier voyage dans le temps.", "Mais celui-là peut attendre ce soir.", "Profite de l'après-midi.<br>On se retrouve un peu plus tard."] } },
  { id: "saturday-evening", challenges: [8, 4] },
];

export const CONFIG = {
  storageKey: "voyage-majorque-v1",
  stateVersion: 4,
  password: "MYMPVTME",
  journeyChapters: JOURNEY_CHAPTERS,
  routeOrder: JOURNEY_CHAPTERS.flatMap(chapter => chapter.challenges),
  chronologicalOrder: [1, 2, 3, 4, 5, 6, 7, 8],
  timeTravel: {
    // Inverser ces deux valeurs suffit à retourner le langage visuel passé/futur.
    visualDirections: { past: "right", future: "left" },
  },
  challengeOne: {
    rules: [
      { id: 1, text: "Marjolaine a toujours raison.", hint: "Avec Marjo, mieux vaut être d’accord !" },
      { id: 2, text: "Vincent doit éplucher<br>et couper les pommes<br>de Marjolaine.", hint: "Vincent n’a qu’une mission :<br>les éplucher, les couper,<br>et les lui servir." },
      { id: 3, text: "Marjolaine a le droit de tremper<br>son chocolat dans le café de Vincent.", hint: "Ce café appartient à Vincent.<br>Le chocolat, beaucoup moins..." },
      { id: 4, text: "Tous les chats sont beaux.", hint: "Cet air ronchon ne change rien :<br>il fait partie de la règle !" },
      { id: 5, text: "On ne doit jamais se coucher<br>en étant fâchés.", hint: "Notre lit est tout petit<br>pour notre amour.<br>Pas question d’y ajouter<br>notre fierté." },
      { id: 6, text: "À la maison, on porte toujours<br>ses chaussons.", hint: "À la maison, il y a<br>une seule façon de circuler...<br>Vincent le sait bien !" },
    ],
  },
  text: {
    opening: {
      welcome: [
        "Je suis un arc-en-ciel.",
        "Je suis né parce que la pluie et le soleil se sont rencontrés.",
        "Je suis né parce que votre voyage a commencé.",
        "On dit souvent que ce n’est pas la destination qui compte, mais le chemin pour y parvenir.",
        "Je ne suis pas tout à fait d’accord.",
        "Je pense que certains voyages restent beaux pour une raison beaucoup plus simple.",
        "Est-ce que tu veux découvrir avec moi pourquoi ?",
      ],
      prologue: [
        "Je t’invite à ouvrir quelques pages,<br>à relever quelques défis,<br>et à te laisser surprendre.",
        "Tu verras des choses que tu n’as encore jamais vues.<br>Des instants qui ont existé sans laisser d’image.<br>Des souvenirs qui auraient mérité d’être gardés quelque part.",
        "Alors je les ai recréés.",
        "Tu verras ce qui a été, ce qui aurait pu être, et peut-être aussi un peu de ce qui pourra être.<br>Des morceaux de votre histoire dont certains restent encore à inventer.",
        "On y va ?",
      ],
      notebook: [
        "C’est lui qui va nous accompagner.<br>Il contiendra les étapes de notre voyage,<br>avec ses défis et ses découvertes.",
        "Prends-le, quand tu es prête.<br>Et laisse-toi guider…",
      ],
    },
    // Provisional copy except D8, whose validated conclusion is unchanged.
    conclusions: {
      1: ["Drôle de façon de construire une histoire d'amour, non ?<br><br>Des pommes coupées, des chaussons, un morceau de chocolat trempé dans un café…<br><br>Ce sont tous ces petits riens qui rendent notre histoire unique.", "Et finalement, ce sont eux qui, petit à petit, ont fabriqué notre « nous ».<br><br>Maintenant, chose promise, chose due : le premier souvenir est là pour toi."],
      2: ["Notre histoire ne tient dans aucune case.<br><br>Elle tient dans des nuits trop courtes,<br>des journées trop remplies,<br>des relais, des fous rires, des moments volés…<br><br>Notre vie à deux a changé.", "Parce qu'un jour,<br>elle est devenue une vie à trois.<br><br>Et le carnet se souvient de ce que ça a changé."],
      3: ["Pas si facile, finalement.<br><br>Quelques mois, les mêmes joues,<br>parfois les mêmes expressions…<br><br>et déjà deux histoires complètement différentes.<br><br>Il y a quelques années,<br>aucun de ces deux petits visages<br>n'existait encore dans notre vie.", "Aujourd'hui, il est difficile<br>d'imaginer notre histoire sans eux.<br><br>Le carnet, lui, se souvient<br>du moment où nous sommes devenus quatre."],
      5: ["Jusqu'ici, le carnet t'a montré<br>des endroits où nous sommes déjà allés.<br><br>Des moments qui existent quelque part<br>derrière nous.<br><br>Mais à partir de maintenant,<br>quelque chose change.<br><br>Les prochaines pages racontent<br>des souvenirs qui n'existent pas encore.", "Des endroits où nous irons peut-être.<br>Des moments que nous vivrons peut-être.<br><br>Et des souvenirs que, pour une fois,<br>nous pouvons commencer à imaginer ensemble."],
      6: ["Ils vous poseront sûrement des centaines de questions.<br><br>Certaines auront une réponse.<br>D'autres beaucoup moins.<br><br>Mais ce qu'ils retiendront surtout,<br>c'est que vous aurez pris le temps d'y répondre.", "Il est temps de voir<br>ce qu'ils auront gardé de tout ça."],
      7: ["Quand on était enfants, on pouvait passer dix minutes à jouer à un jeu comme celui-ci.<br><br>Puis recommencer.<br>Et recommencer encore.<br><br>La vie était belle, on avait le temps devant nous.<br><br>Et puis un jour, sans vraiment s'en rendre compte, on devient les parents.", "Et oui… les années ont passé.<br>Les enfants ont grandi.<br><br>Et le carnet commence maintenant à imaginer ce qu'ils deviendront."],
      8: ["Il y a des chansons qu'on reconnaît en quelques secondes.", "Et d'autres qu'on n'oublie jamais."],
      4: ["Tu étais là.<br><br>Au bon endroit,<br>au bon moment.", "Ce dernier souvenir est à toi."],
    },
    diagnostic: "Votre histoire ne tient dans aucune case.",
  },
  chapters: {
    1: {
      title: "Stresa",
      publicChallengeTitle: "Les règles de notre monde",
      galleryTitle: "Stresa",
      letter: "M",
      memoryThumbnail: "assets/challenge-1/v1-4-27/parc-de-vincennes.png",
      gallery: [
        { id: "vincennes-01", full: "assets/challenge-1/v1-4-30/d1-vincennes-portrait-characters.png", decor: "assets/challenge-1/v1-4-30/d1-vincennes-portrait-decor.png", immersive: true, alt: "Vincent et Marjolaine sur le banc du parc de Vincennes" },
        { id: "duomo-02", decor: "assets/challenge-1/v1-4-45/D1_G2_decor.png", full: "assets/challenge-1/v1-4-45/D1_G2_final.png", alt: "Vincent et Marjolaine devant le Duomo" },
        { id: "D1_G3", decor: "assets/challenge-1/v1-4-45/D1_G3_decor.png", full: "assets/challenge-1/v1-4-45/D1_G3_final.png", alt: "Vincent, Marjolaine enceinte et leur chat devant le mur de miroirs" },
        { id: "D1_G4", decor: "assets/challenge-1/v1-4-45/D1_G4_decor.png", full: "assets/challenge-1/v1-4-45/D1_G4_final.png" },
        { id: "D1_G5", decor: "assets/challenge-1/v1-4-45/D1_G5_decor.png", full: "assets/challenge-1/v1-4-45/D1_G5_final.png", alt: "Vincent et Marjolaine au balcon du Regina Palace à Stresa" },
      ],
      // Option future : { enabled: true, src: "assets/audio/...", startMode: "user", volume: 0.8 }
      soundtrack: null,
    },
    2: {
      title: "La vie à trois",
      publicChallengeTitle: "Notre profil de couple",
      galleryTitle: "Regarde.",
      letter: "Y",
      gallery: [
        { id: "D2_G1", decor: "assets/challenge-1/v1-4-45/D2_G1_decor.png", full: "assets/challenge-1/v1-4-45/D2_G1_final.png" },
        { id: "D2_G2", decor: "assets/challenge-1/v1-4-45/D2_G2_decor.png", full: "assets/challenge-1/v1-4-45/D2_G2_final.png" },
        { id: "D2_G3", decor: "assets/challenge-1/v1-4-45/D2_G3_decor.png", full: "assets/challenge-1/v1-4-45/D2_G3_final.png" },
        { id: "D2_G4", decor: "assets/challenge-1/v1-4-45/D2_G4_decor.png", full: "assets/challenge-1/v1-4-45/D2_G4_final.png" },
        { id: "D2_G5", decor: "assets/challenge-1/v1-4-45/D2_G5_decor.png", full: "assets/challenge-1/v1-4-45/D2_G5_final.png" },
      ],
      soundtrack: null,
      profiles: {
        A: { symbol: "◆", name: "L’équipe organisée", description: "Planning, relais, organisation : vous aimez sentir que les choses sont sous contrôle… ou au moins faire semblant." },
        B: { symbol: "●", name: "Tendrement débordés", description: "Vous avez compris l’essentiel : parfois, aimer quelqu’un, c’est surtout lui dire “vas-y, je m’en occupe”." },
        C: { symbol: "✦", name: "Complices dans le chaos", description: "Chez vous, les galères ont une drôle de tendance à finir en blagues et en souvenirs." },
        D: { symbol: "♡", name: "Les amoureux avant tout", description: "Le couple n’a pas disparu sous la logistique, la fatigue et les journées trop remplies. Il a juste trouvé de nouvelles façons de se dire “je t’aime”." },
      },
      questions: [
        { prompt: "Votre définition d’un moment romantique depuis que vous êtes parents ?", options: [
          { symbol: "●", profile: "B", text: "Dix minutes tranquilles sur le canapé, ça compte déjà beaucoup." },
          { symbol: "✦", profile: "C", text: "Un fou rire au milieu d’un moment complètement bancal." },
          { symbol: "♡", profile: "D", text: "Un moment où on se retrouve vraiment tous les deux, même très court." },
          { symbol: "◆", profile: "A", text: "Un vrai dîner à deux, organisé à l’avance." },
        ] },
        { prompt: "Votre couple face au manque de sommeil, c’est…", options: [
          { symbol: "◆", profile: "A", text: "Une équipe qui se répartit les rôles." },
          { symbol: "✦", profile: "C", text: "Deux zombies qui finissent par rire de leur état." },
          { symbol: "●", profile: "B", text: "Deux zombies qui essaient de se relayer gentiment." },
          { symbol: "♡", profile: "D", text: "Deux zombies qui trouvent encore le moyen de se faire un câlin." },
        ] },
        { prompt: "Quand vous avez enfin une soirée à deux, vous choisissez quoi ?", options: [
          { symbol: "♡", profile: "D", text: "Peu importe ce qu’on fait, du moment qu’on est vraiment ensemble." },
          { symbol: "✦", profile: "C", text: "Improviser au dernier moment selon l’humeur." },
          { symbol: "◆", profile: "A", text: "Quelque chose de prévu pour vraiment en profiter." },
          { symbol: "●", profile: "B", text: "Ne rien faire et récupérer ensemble." },
        ] },
        { prompt: "Dans votre couple, le romantisme aujourd’hui ressemble plutôt à…", options: [
          { symbol: "◆", profile: "A", text: "Des attentions préparées à l’avance." },
          { symbol: "♡", profile: "D", text: "Un bisou, une main posée sur l’autre, un regard qui veut tout dire." },
          { symbol: "●", profile: "B", text: "Des petits gestes pratiques qui soulagent l’autre." },
          { symbol: "✦", profile: "C", text: "Des blagues privées que personne d’autre ne comprend." },
        ] },
        { prompt: "Si votre vie de famille était une météo, ce serait…", options: [
          { symbol: "●", profile: "B", text: "Quelques averses, mais on reste bien à l’abri ensemble." },
          { symbol: "♡", profile: "D", text: "Un temps changeant, avec toujours un petit coin de ciel bleu à deux." },
          { symbol: "✦", profile: "C", text: "Une petite tempête suivie d’un grand arc-en-ciel." },
          { symbol: "◆", profile: "A", text: "Un ciel changeant mais surveillé de près." },
        ] },
        { prompt: "Quand l’un de vous est épuisé, l’autre…", options: [
          { symbol: "♡", profile: "D", text: "Commence par vérifier qu’il va vraiment bien." },
          { symbol: "◆", profile: "A", text: "Réorganise immédiatement la journée pour prendre le relais." },
          { symbol: "✦", profile: "C", text: "Commence par le faire rire avant de prendre la suite." },
          { symbol: "●", profile: "B", text: "Fait ce qu’il peut pour alléger la charge." },
        ] },
        { prompt: "Votre plus grande force à deux ?", options: [
          { symbol: "●", profile: "B", text: "Savoir vous soutenir." },
          { symbol: "✦", profile: "C", text: "Savoir rire ensemble." },
          { symbol: "♡", profile: "D", text: "Ne jamais vraiment vous perdre de vue." },
          { symbol: "◆", profile: "A", text: "Savoir vous organiser." },
        ] },
        { prompt: "À la fin d’une longue journée, votre geste préféré ?", options: [
          { symbol: "✦", profile: "C", text: "Se regarder avec l’air de dire « on a survécu »." },
          { symbol: "●", profile: "B", text: "S’affaler côte à côte et souffler enfin." },
          { symbol: "◆", profile: "A", text: "Faire le point ensemble sur ce qu’il reste à gérer." },
          { symbol: "♡", profile: "D", text: "Se rapprocher l’un de l’autre, même sans parler." },
        ] },
        { prompt: "Ce qui vous ressemble le plus depuis que vous êtes parents ?", options: [
          { symbol: "♡", profile: "D", text: "Toujours amoureux, mais autrement." },
          { symbol: "●", profile: "B", text: "Plus attentifs l’un à l’autre qu’avant." },
          { symbol: "◆", profile: "A", text: "Plus organisés qu’avant." },
          { symbol: "✦", profile: "C", text: "Encore plus complices dans l’imprévu." },
        ] },
        { prompt: "Quand vous repensez à votre vie “avant”, vous vous dites…", options: [
          { symbol: "✦", profile: "C", text: "« On avait déjà de bons souvenirs, mais pas ceux-là. »" },
          { symbol: "♡", profile: "D", text: "« Notre vie a changé, mais j’aime toujours autant être juste avec toi. »" },
          { symbol: "◆", profile: "A", text: "« On avait tellement moins de choses à organiser. »" },
          { symbol: "●", profile: "B", text: "« On ne savait pas ce que voulait dire être vraiment fatigués. »" },
        ] },
        { prompt: "Si votre couple avait un super-pouvoir, ce serait…", options: [
          { symbol: "●", profile: "B", text: "Continuer à avancer même avec très peu d’énergie." },
          { symbol: "♡", profile: "D", text: "Réussir à se retrouver même quand tout le reste prend toute la place." },
          { symbol: "◆", profile: "A", text: "Anticiper les catastrophes." },
          { symbol: "✦", profile: "C", text: "Transformer le chaos en complicité." },
        ] },
        { prompt: "Au fond, votre nouvelle vie ressemble surtout à…", options: [
          { symbol: "♡", profile: "D", text: "Une histoire d’amour qui a grandi pour faire de la place à quelqu’un d’autre." },
          { symbol: "◆", profile: "A", text: "Un équilibre qu’on construit et qu’on ajuste chaque jour." },
          { symbol: "●", profile: "B", text: "Une équipe qui apprend à se soutenir dans la fatigue." },
          { symbol: "✦", profile: "C", text: "Une aventure imprévisible qui devient votre histoire préférée." },
        ] },
      ],
    },
    3: {
      title: "La vie à quatre",
      publicChallengeTitle: "Qui est qui ?",
      galleryTitle: "Regarde.",
      letter: "M",
      gallery: [
        { id: "D3_G1", decor: "assets/challenge-3/v1-4-58/D3_G1_decor.png", full: "assets/challenge-3/v1-4-58/D3_G1_final.png" },
        { id: "D3_G2", decor: "assets/challenge-3/v1-4-58/D3_G2_decor.png", full: "assets/challenge-3/v1-4-58/D3_G2_final.png" },
        { id: "D3_G3", decor: "assets/challenge-3/v1-4-58/D3_G3_decor.png", full: "assets/challenge-3/v1-4-58/D3_G3_final.png" },
      ],
      soundtrack: null,
      babyPhotos: [
        {"id": "lenny-01", "src": "assets/challenge-3/crop-calibrator/Lenny_Full_2.jpeg", "answer": "lenny", "difficulty": "medium", "crop": {"x": 32.5, "y": 9.8, "width": 42.9, "height": 36.5}},
        {"id": "lenny-02", "src": "assets/challenge-3/crop-calibrator/Lenny_Full_4.jpeg", "answer": "lenny", "difficulty": "hard", "crop": {"x": 31.6, "y": 43.4, "width": 33.6, "height": 19.8}},
        {"id": "lenny-03", "src": "assets/challenge-3/crop-calibrator/Lenny_Full_5.jpeg", "answer": "lenny", "difficulty": "very-hard", "crop": {"x": 29.6, "y": 17, "width": 31.5, "height": 12.4}},
        {"id": "lenny-04", "src": "assets/challenge-3/crop-calibrator/Lenny_Full_6.jpeg", "answer": "lenny", "difficulty": "medium", "crop": {"x": 54.6, "y": 51.2, "width": 34.5, "height": 22.2}},
        {"id": "lenny-05", "src": "assets/challenge-3/crop-calibrator/Lenny_Full_7.jpeg", "answer": "lenny", "difficulty": "easy", "crop": {"x": 31.6, "y": 15.9, "width": 43.3, "height": 21.2}},
        {"id": "lenny-06", "src": "assets/challenge-3/crop-calibrator/Lenny_Full_9.jpeg", "answer": "lenny", "difficulty": "medium", "crop": {"x": 17, "y": 27.7, "width": 48.2, "height": 47.1}},
        {"id": "lenny-07", "src": "assets/challenge-3/crop-calibrator/Lenny_Full_10.jpeg", "answer": "lenny", "difficulty": "very-hard", "crop": {"x": 35.2, "y": 19.1, "width": 21.6, "height": 10.7}},
        {"id": "lenny-08", "src": "assets/challenge-3/crop-calibrator/Lenny_Full_11.jpeg", "answer": "lenny", "difficulty": "hard", "crop": {"x": 15.8, "y": 28.8, "width": 50.9, "height": 34.9}},
        {"id": "lenny-09", "src": "assets/challenge-3/crop-calibrator/Lenny_Full_14.jpeg", "answer": "lenny", "difficulty": "hard", "crop": {"x": 25.7, "y": 24.3, "width": 25.8, "height": 23.5}},
        {"id": "lenny-10", "src": "assets/challenge-3/crop-calibrator/Lenny_Full_16.jpeg", "answer": "lenny", "difficulty": "very-hard", "crop": {"x": 39.5, "y": 20.8, "width": 26.3, "height": 10.2}},
        {"id": "milan-01", "src": "assets/challenge-3/crop-calibrator/Milan_Full_1.JPG", "answer": "milan", "difficulty": "medium", "crop": {"x": 21.8, "y": 12.7, "width": 29.7, "height": 30.3}},
        {"id": "milan-02", "src": "assets/challenge-3/crop-calibrator/Milan_Full_3.JPG", "answer": "milan", "difficulty": "hard", "crop": {"x": 32.1, "y": 20.2, "width": 21.4, "height": 15.1}},
        {"id": "milan-03", "src": "assets/challenge-3/crop-calibrator/Milan_Full_4.JPG", "answer": "milan", "difficulty": "easy", "crop": {"x": 13.6, "y": 4.5, "width": 53.7, "height": 46.4}},
        {"id": "milan-04", "src": "assets/challenge-3/crop-calibrator/Milan_Full_5.JPG", "answer": "milan", "difficulty": "very-hard", "crop": {"x": 31, "y": 15.6, "width": 23.5, "height": 12.4}},
        {"id": "milan-05", "src": "assets/challenge-3/crop-calibrator/Milan_Full_7.JPG", "answer": "milan", "difficulty": "hard", "crop": {"x": 33.7, "y": 9.5, "width": 30.9, "height": 19.7}},
        {"id": "milan-06", "src": "assets/challenge-3/crop-calibrator/Milan_Full_9.JPG", "answer": "milan", "difficulty": "hard", "crop": {"x": 24.2, "y": 17.4, "width": 34.6, "height": 28.9}},
        {"id": "milan-07", "src": "assets/challenge-3/crop-calibrator/Milan_Full_10.jpeg", "answer": "milan", "difficulty": "medium", "crop": {"x": 11.9, "y": 0, "width": 64.2, "height": 53.8}},
        {"id": "milan-08", "src": "assets/challenge-3/crop-calibrator/Milan_Full_14.JPG", "answer": "milan", "difficulty": "very-hard", "crop": {"x": 57.2, "y": 57.9, "width": 13.4, "height": 9.2}},
        {"id": "milan-09", "src": "assets/challenge-3/crop-calibrator/Milan_Full_15.JPG", "answer": "milan", "difficulty": "easy", "crop": {"x": 32.7, "y": 4.4, "width": 35.4, "height": 32}},
        {"id": "milan-10", "src": "assets/challenge-3/crop-calibrator/IMG_3281.JPG", "answer": "milan", "difficulty": "hard", "crop": {"x": 43.4, "y": 26.1, "width": 19.4, "height": 11.2}}
      ],
    },
    4: {
      title: "Majorque",
      publicChallengeTitle: "Le coucher de soleil",
      galleryTitle: "Majorque",
      letter: "P",
      gallery: [{ id: "D4_G1", decor: "assets/challenge-4/v1-4-59/D4_G1_decor.png", full: "assets/challenge-4/v1-4-59/D4_G1_final.png" }],
      soundtrack: null,
    },
    5: {
      title: "Stockholm",
      publicChallengeTitle: "À toi de nous emmener à Stockholm",
      galleryTitle: "Stockholm",
      letter: "V",
      gallery: [
        { id: "D5_G1", decor: "assets/challenge-5/v1-4-59/D5_G1_decor.png", full: "assets/challenge-5/v1-4-59/D5_G1_final.png" },
        { id: "D5_G2", decor: "assets/challenge-1/v1-4-45/D5_G2_decor.png", full: "assets/challenge-1/v1-4-45/D5_G2_final.png" },
        { id: "D5_G3", decor: "assets/challenge-1/v1-4-45/D5_G3_decor.png", full: "assets/challenge-1/v1-4-45/D5_G3_final.png" },
        { id: "D5_G4", decor: "assets/challenge-5/v1-4-59/D5_G4_decor.png", full: "assets/challenge-5/v1-4-59/D5_G4_final.png" },
        { id: "D5_G5", decor: "assets/challenge-5/v1-4-59/D5_G5_decor.png", full: "assets/challenge-5/v1-4-59/D5_G5_final.png" },
        { id: "D5_G6", decor: "assets/challenge-5/v1-4-59/D5_G6_decor.png", full: "assets/challenge-5/v1-4-59/D5_G6_final.png" },
      ],
      soundtrack: null,
      routeEvents: [
        { text: "La route s’ouvre devant nous.", action: "Démarrer" },
        { text: "Une pause imprévue. L’arc-en-ciel prétend connaître un raccourci.", action: "Reprendre la route" },
        { text: "La Baltique n’est plus très loin.", action: "Continuer vers le nord" },
      ],
    },
    6: {
      title: "Retour en France",
      publicChallengeTitle: "À vous de les convaincre",
      galleryTitle: "Regarde.",
      letter: "T",
      gallery: [
        { id: "D6_G1", decor: "assets/challenge-6/v1-4-61/D6_G1_decor.png", full: "assets/challenge-6/v1-4-61/D6_G1_final.png" },
        { id: "D6_G2", decor: "assets/challenge-6/v1-4-61/D6_G2_decor.png", full: "assets/challenge-6/v1-4-61/D6_G2_final.png" },
        { id: "D6_G3", decor: "assets/challenge-6/v1-4-61/D6_G3_decor.png", full: "assets/challenge-6/v1-4-61/D6_G3_final.png" },
        { id: "D6_G4", decor: "assets/challenge-6/v1-4-61/D6_G4_decor.png", full: "assets/challenge-6/v1-4-61/D6_G4_final.png" },
      ],
      soundtrack: null,
    },
    7: {
      title: "Adolescence",
      publicChallengeTitle: "Le serpent",
      galleryTitle: "Regarde.",
      letter: "M",
      gallery: [{ src: null, label: "PLACEHOLDER — ADOLESCENCE" }],
      soundtrack: null,
    },
    8: {
      title: "Futur lointain",
      publicChallengeTitle: "Blind test guitare",
      galleryTitle: "Regarde.",
      letter: "E",
      gallery: [{ src: null, label: "PLACEHOLDER — FUTUR LOINTAIN" }],
      soundtrack: null,
      songs: [
        { title: "Lady Marmalade", artist: "Christina Aguilera" },
        { title: "Set Fire to the Rain", artist: "Adele" },
        { title: "Bohemian Rhapsody", artist: "Queen" },
        { title: "Ave Maria", artist: "Andrea Bocelli" },
        { title: "Your Song", artist: "Elton John" },
        { title: "Still Loving You", artist: "Scorpions" },
        { title: "Can’t Help Falling in Love", artist: "Elvis Presley" },
      ],
    },
  },
};

export const STEPS = [
  "welcome", "prologue", "notebook-intro",
  ...CONFIG.routeOrder.flatMap(id => [
    `challenge-${id}`, `conclusion-${id}`,
    `gallery-${id}`, `handoff-${id}`,
    ...JOURNEY_CHAPTERS.filter(chapter => chapter.pause?.after === id).map(chapter => chapter.pause.id),
  ]),
  "password", "final-handover", "final",
].map(id => ({ id, label: id.replaceAll("-", " ") }));
